# Convoluciones

En simples términos queremos llegar a:

f(x) * g(x) = h(x)

Una manera de combinar 2 funciones para generar una nueva función

Tenemos 2 listas: a y b y queremos combinarlas

a = [1,2,3,4]
b = [5,6,7,8]

Adicion (element-wise)
a + b = [6,8,10,12]

Multiplicacion (element-wise)
a.b = [5,12,21,32]

## Convolucion

a*b = (f*g)(f) integral -inf x f(x) ,g(fx)dx

### Convoluciones discretas

### Probabilidad

Lanzar 2 dados y conocer la probabilidad de cada una de las posibles sumas

- 36 combianciones posibles (matriz de 6x6)

In [1]:
import numpy as np

# Create a 6x6 matrix with row and column indices from 1 to 6
matrix = np.zeros((6, 6))

for i in range(6):
    for j in range(6):
        matrix[i][j] = (i + 1) + (j + 1)  # Sum of dice values

print("6x6 Matrix showing sum of two dice:")
print(matrix.astype(int))

6x6 Matrix showing sum of two dice:
[[ 2  3  4  5  6  7]
 [ 3  4  5  6  7  8]
 [ 4  5  6  7  8  9]
 [ 5  6  7  8  9 10]
 [ 6  7  8  9 10 11]
 [ 7  8  9 10 11 12]]


Todas las sumas constantes son visibles en las diagonales

* P(d1 + d2 = 2) = 1/36
* P(d1 + d2 = 3) = 2/36

Otra manera?
Vamos a rotar la matriz de dados rojos

Alineando de otra manera
Los pares suman 2
Los pares suman 3

Por que estamos contando los pares que se alinean con la suma de los dados?

Casos + / Total casos

Asumiendo que la probabilidad es constante y para un dado es
p = 1/6

Que pasa si las caras de los dados no tienen igual probabilidad?

P (d1 + d2 = 2) = P(d1) * P(d2)

Convolucion de a y b

a*b = Sum i,j ai . bi (i+j = n)

In [2]:
np.convolve((1,2,3),(4,5,6))

array([ 4, 13, 28, 27, 18])